[package]
name = "directory_structure_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3.2"
ignore = "0.4.23"
clap = { version = "4.5.17", features = ["derive"] }
tempfile = "3.12.0"

[dev-dependencies]
tempfile = "3.2"

