name: Release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to build for'
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_name: dirtree-macos-intel
          - os: macos-latest
            target: aarch64-apple-darwin
            binary_name: dirtree-macos-arm
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_name: dirtree-linux

    steps:
      - uses: actions/checkout@v4
      - name: Get release
        id: get_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
      - name: Rename binary
        run: mv target/${{ matrix.target }}/release/dirtree ${{ matrix.binary_name }}
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.binary_name }}
          tag_name: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}